version: "3.8"

networks:
  docknode-sui:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  fullnode_data:

services:
  fullnode:
    image: "mysten/sui-node:mainnet"
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9184:9184"
      - "9000:9000"
      - "8084:8084/udp"
    volumes:
      - ./sui/fullnode.yaml:/sui/fullnode.yaml:ro
      - ./sui/fullnode.yaml:/opt/sui/config/fullnode.yaml:ro
      - ./sui/genesis.blob:/sui/genesis.blob:ro
      - ./sui/genesis.blob:/opt/sui/config/genesis.blob:ro
      - fullnode_data:/sui/suidb:rw
    command:
      [
        "/opt/sui/bin/sui-node",
        "--config-path",
        "/opt/sui/config/fullnode.yaml",
      ]
    networks:
      - docknode-sui

  nodeexporter:
    image: prom/node-exporter:v1.4.0
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - docknode-sui

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 9101:9101
      - 9102:9102
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - METRICS_USERS=${METRICS_USERS:?err}
      - RPC_USERS=${RPC_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-sui
